name: CI_CodeChecks

on: 
   workflow_dispatch:

jobs:
  #Run cppcheck off FlameSheet
  CppCheck:
    name: CppCheck [FS2D]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Dependencies
      run: |
        sudo apt-get install -y python3-setuptools 
        python3 -m pip install --user wheel
        python3 -m pip install --user compiledb   
        brew install cppcheck
    - name: Repo Dependencies
      run: Tools/CloneDeps.sh
    - name: Build
      env:
         AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
         IAMR_HOME: ${GITHUB_WORKSPACE}/build/IAMR
         PELE_PHYSICS_HOME: ${GITHUB_WORKSPACE}/build/PelePhysics
         PELELM_HOME: ${GITHUB_WORKSPACE}
      run: |
        cd Exec/RegTests/FlameSheet/
        make TPL COMP=gnu USE_MPI=FALSE
        python3 -m compiledb make COMP=gnu USE_MPI=FALSE
        cppcheck --inline-suppr --suppress=unmatchedSuppression --std=c++14 \
            --language=c++ --enable=all --project=compile_commands.json \
            --file-filter=${GITHUB_WORKSPACE}/Source/PeleLM* --output-file=cppcheck.txt
        cat cppcheck.txt
